spring:
  application:
    name: brain-gym-academy-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/brain_gym_academy}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:PasswordPlaceholder}
    # Hikari Connection Pool Optimizations to match Neon's serverless idling
    hikari:
      max-lifetime: 240000     # 4 minutes in milliseconds (cycles connections before Neon drops them)
      keepalive-time: 60000    # 1 minute in milliseconds (regularly pings connections to keep them hot)
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

server:
  port: 8080
